---
abstract: 'Template View Class'
author:
  - 'Sebastian Riedel, C<sri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.6302
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.6302
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-TT
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.7
  Class::Accessor: 0
  MRO::Compat: 0
  Path::Class: 0
  Template: 0
  Template::Timer: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/catagits/Catalyst-View-TT.git
version: 0.38
